### ISSUE TITLE
RFC: frame introspection

### ISSUE THREAD

**Issue by ShineyDev** [ShineyDev/pretty#3]
two ideas behind this one; "context" and "look around"

"context" is essentially just multiple lines displayed in a frame. this *can* help in finding out-of-reach exception causes.

let's create a snippet for these examples;
```py
if (divisor := some_cls.attribute) is not None:
    return bar(10.,
               divisor)
```

when `bar` raises, `ast.parse("return bar(10.,", filename, "exec")` is called, producing a SyntaxError. when this happens, or optionally at all times, we can show N (here: 1) surrounding lines in the frame. like so;
```
  File 'cool.py', line 100, in foo()
    [...]
    if (divisor := some_cls.attribute) is not None:
        return bar(10.,
                   divisor)
    [...]
```

note that this can still raise a SyntaxError, unlike "look around".

PROS:
- the pros of this are obvious if you've ever had to debug anything

CONS:
- locked to a specific N; unlike "look around", this concept will display N lines above and below the frame, in all frames - whether it helps or hinders depends on N.

"look around", however, is more complex and will *look around* the frame in the case of a SyntaxError from `ast.parse`. it's best I solely show examples for this one.

assuming the same example as above, when `bar` raises, blah, blah, SyntaxError. when this happens we (somehow) figure out where to go from there, in the hopes of generating a minimal AST. like so;
```
  File 'cool.py', line 100, in foo()
    [...]
    return bar(10.,
               divisor)
    [...]
```

PROS:
- any pros from context, plus;
- not locked to N

CONS:
- the complexity that comes with making this work **well** is high
- ugh AST

**Comment by IAmTomahawkx** [comment]
i think that look around, although obviously a much nicer format, is a longer term goal, where the context option is a much more short-term achievable goal, and probably easier resource-wise (note that i actually have no clue). maybe have two different hook options + two seperate env variables?

**Comment by ShineyDev** [comment]
> look around, although obviously a much nicer format, is a longer-term goal

I agree,

> maybe have two different hook options + two separate env variables

not-so here.

two `_Formatter` kwargs seems unnecessary, while one `introspection?=Optional[str]` kwarg much more plausible. though this makes for setting N for "context" a drawback.

also, I'd like for this library to minimize the use of exclusive environment variables;
- `PY_PRETTIFY_EXC`, an exclusive env-var, is used to hook prettify into all python runners.
- [`NO_COLOR`](https://no-color.org/), an (rfc-backed?) env-var, used to mark all software as non-ansi-outputting.

adding more - unless completely necessary - is not likely to happen

**Comment by ShineyDev** [comment]
boop @idutchy @kaylynn234 @lganwebb @mynamebemrrandom

**Comment by lgaan** [comment]
I boop back @ShineyDev

**Comment by aaronhnsy** [comment]
I agree with Tom that while it would be nice to have the 2nd option, the 1st option would be more than enough for me. The second option would only really remove a few lines if i'm understanding correctly so I don't see much of a benefit.
